export const ENGLISH_ALIASES: Record<string, string[]> = {
  share: ['share', 'shares', 'stock', 'stocks', 'equity', 'equities'],
  shareholder: ['shareholder', 'shareholders'],
  'market-capitalisation': [
    'market cap',
    'market capitalisation',
    'market capitalization',
  ],
  bond: ['bond', 'bonds'],
  coupon: ['coupon'],
  yield: ['yield', 'yields'],
  dividend: ['dividend', 'dividends'],
  'dividend-yield': ['dividend yield'],
  'payout-ratio': ['payout ratio'],
  buyback: ['buyback', 'buybacks', 'share buyback', 'repurchase'],
  'shares-outstanding': ['shares outstanding'],
  dilution: ['dilution', 'dilutive'],
  'stock-split': ['stock split'],
  'reverse-split': ['reverse split'],
  ipo: ['ipo', 'flotation'],
  'lock-up-period': ['lock-up', 'lockup'],
  underwriter: ['underwriter', 'underwriters'],

  index: ['index', 'indices', 'indexes'],
  'index-fund': ['index fund', 'index funds'],
  'expense-ratio': ['expense ratio', 'ongoing charge'],
  'passive-fund': ['passive fund', 'passive funds'],
  'active-fund': ['active fund', 'active funds', 'actively managed'],
  'mutual-fund': ['mutual fund', 'mutual funds'],
  diversification: ['diversification', 'diversified'],
  'tracking-error': ['tracking error'],
  benchmark: ['benchmark', 'benchmarks'],

  revenue: ['revenue', 'revenues', 'sales'],
  'operating-margin': ['operating margin', 'operating margins'],
  'free-cash-flow': ['free cash flow', 'cash flow'],
  'earnings-per-share': ['earnings per share', 'eps'],
  'pe-ratio': ['p/e', 'pe ratio', 'price-to-earnings'],
  guidance: ['guidance', 'outlook', 'forecast'],
  'consensus-estimate': ['consensus estimate', 'analyst estimates'],
  'shareholders-equity': ['shareholders equity', 'book value'],
  leverage: ['leverage', 'leveraged'],
  'growth-stock': ['growth stock', 'growth stocks'],
  'value-stock': ['value stock', 'value stocks'],

  inflation: ['inflation', 'inflationary'],
  cpi: ['cpi', 'consumer price index'],
  'core-inflation': ['core inflation', 'core cpi'],
  deflation: ['deflation'],
  'policy-rate': ['policy rate', 'interest rate', 'interest rates', 'rates'],
  'basis-point': ['basis point', 'basis points', 'bps'],
  'monetary-policy': ['monetary policy'],
  'central-bank': ['central bank', 'central banks', 'the fed', 'ecb'],
  'forward-guidance': ['forward guidance'],
  'quantitative-easing': ['quantitative easing'],
  hawkish: ['hawkish', 'dovish'],
  gdp: ['gdp', 'gross domestic product'],
  'real-gdp': ['real gdp'],
  recession: ['recession', 'recessions'],
  'business-cycle': ['business cycle'],
  'soft-landing': ['soft landing'],
  'yield-curve': ['yield curve'],
  inversion: ['inverted yield curve', 'curve inversion'],
  'nonfarm-payrolls': ['nonfarm payrolls', 'payrolls'],
  'unemployment-rate': ['unemployment rate', 'unemployment'],
  'wage-growth': ['wage growth', 'wages'],
  'exchange-rate': ['exchange rate'],
  'safe-haven': ['safe haven'],
  'reserve-currency': ['reserve currency'],
  commodity: ['commodity', 'commodities'],
  'supply-shock': ['supply shock'],

  'bid-ask-spread': ['spread', 'spreads', 'bid-ask'],
  liquidity: ['liquidity', 'liquid', 'illiquid'],
  'market-maker': ['market maker', 'market makers'],
  volatility: ['volatility', 'volatile'],
  volume: ['trading volume'],
  broker: ['broker', 'brokers', 'brokerage'],
  'limit-order': ['limit order'],
  'market-order': ['market order'],
  sector: ['sector', 'sectors'],
  'sector-rotation': ['sector rotation'],
  correlation: ['correlation', 'correlated'],
  drawdown: ['drawdown', 'drawdowns'],
  'bear-market': ['bear market'],
  'bull-market': ['bull market'],
  correction: ['market correction'],

  portfolio: ['portfolio', 'portfolios'],
  'asset-allocation': ['asset allocation'],
  rebalancing: ['rebalancing', 'rebalance'],
  'capital-gain': ['capital gain', 'capital gains'],
  'currency-risk': ['currency risk', 'fx risk'],
  hedged: ['hedged', 'hedging'],
  'margin-call': ['margin call'],
  'counterparty-risk': ['counterparty risk'],
  compounding: ['compound interest'],
  'real-return': ['real return', 'real returns'],
};
